name: "Deploy"
on:
  release:
    types:
      - created
jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.20
        with:
          github_token: ${{ secrets.TOKEN }}
          goos: linux
          goarch: amd64
          binary_name: env-templater
          project_path: ./cmd/env-templater
          ld_flags: "-s -w"